FROM postgres
RUN apt-get update && apt-get install -y python3
COPY /sql/generate_data.py /docker-entrypoint-initdb.d/
COPY /sql/init.sql /docker-entrypoint-initdb.d/
COPY /sql/entrypoint.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/generate_data.py