version: '3.8'
services:
  appadd:
    image: foxlover/java_project_hl:LAB9_ADD
    container_name: additional
    ports:
      - "8081:8081"
    networks:
      - postgres_network
    mem_limit: 2048M
    mem_reservation: 256M
    cpus: '1'
    environment:
      - SERVER_PORT=8081
      - SERVER_ADDRESS=0.0.0.0

  app:
    extra_hosts:
      - "hl22.zil:127.0.0.2"
      - "hl23.zil:127.0.0.3"
    image: foxlover/java_project_hl:KAFKA
    container_name: main
    ports:
      - "8080:8080"
    networks:
      - postgres_network
    mem_limit: 2048M
    mem_reservation: 256M
    cpus: '1'
    environment:
      - SERVER_TOMCAT_MAX_THREADS=200
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.60.3.26:5432/sirius_java_bd
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_JPA_SHOW_SQL=false

networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
