apiVersion: apps/v1
kind: Deployment
metadata:
  name: additional
  namespace: var13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: additional
  template:
    metadata:
      labels:
        app: additional
    spec:
      containers:
        - name: additional
          image: foxlover/java_project_hl:LAB9_ADD
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "1024Mi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: SERVER_ADDRESS
              value: "0.0.0.0"