apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  namespace: var13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
        - name: main
          image: foxlover/java_project_hl:LAB14
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1000m"
            requests:
              memory: "256Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets